name: Euler
icon: logo.png
category: Money Market
url: https://app.euler.finance/borrow?network=ethereum
description: >-
  Euler is a modular lending platform that enables users to lend, borrow and
  build without limits.
metadata:
  pt:
  sy:
  lp:
