name: Aave
icon: logo.png
category: Money Market
description: >-
  Aave is a decentralised non-custodial liquidity protocol where users can
  participate as suppliers or borrowers
url: https://app.aave.com/
metadata:
  pt:
    - chainId: 1
      address: '0x62C6E813b9589C3631Ba0Cdb013acdB8544038B7'
      subtitle: USDC
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x62c6e813b9589c3631ba0cdb013acdb8544038b7&marketName=proto_ethereum_v3
      description: PT-USDe-27NOV2025 can be used as collateral to borrow USDC on Aave
    - chainId: 1
      address: '0x62C6E813b9589C3631Ba0Cdb013acdB8544038B7'
      subtitle: USDT
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x62c6e813b9589c3631ba0cdb013acdb8544038b7&marketName=proto_ethereum_v3
      description: PT-USDe-27NOV2025 can be used as collateral to borrow USDT on Aave
    - chainId: 1
      address: '0xe6A934089BBEe34F832060CE98848359883749B3'
      subtitle: USDC
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0xe6a934089bbee34f832060ce98848359883749b3&marketName=proto_ethereum_v3
      description: PT-sUSDE-27NOV2025 can be used as collateral to borrow USDC on Aave
    - chainId: 1
      address: '0xe6A934089BBEe34F832060CE98848359883749B3'
      subtitle: USDT
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0xe6a934089bbee34f832060ce98848359883749b3&marketName=proto_ethereum_v3
      description: PT-sUSDE-27NOV2025 can be used as collateral to borrow USDT on Aave
    - chainId: 9745
      address: '0x93B544c330F60A2aa05ceD87aEEffB8D38FD8c9a'
      subtitle: USDC
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x93b544c330f60a2aa05ced87aeeffb8d38fd8c9a&marketName=proto_plasma_v3
      description: PT-USDe-15JAN2026 can be used as collateral to borrow USDC on Aave
    - chainId: 9745
      address: '0x93B544c330F60A2aa05ceD87aEEffB8D38FD8c9a'
      subtitle: USDT
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x93b544c330f60a2aa05ced87aeeffb8d38fd8c9a&marketName=proto_plasma_v3
      description: PT-USDe-15JAN2026 can be used as collateral to borrow USDT on Aave
    - chainId: 9745
      address: '0x02FCC4989B4C9D435b7ceD3fE1Ba4CF77BBb5Dd8'
      subtitle: USDC
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x02fcc4989b4c9d435b7ced3fe1ba4cf77bbb5dd8&marketName=proto_plasma_v3
      description: PT-sUSDE-15JAN2026 can be used as collateral to borrow USDC on Aave
    - chainId: 9745
      address: '0x02FCC4989B4C9D435b7ceD3fE1Ba4CF77BBb5Dd8'
      subtitle: USDT
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x02fcc4989b4c9d435b7ced3fe1ba4cf77bbb5dd8&marketName=proto_plasma_v3
      description: PT-sUSDE-15JAN2026 can be used as collateral to borrow USDT on Aave
  yt: []
  lp: []
